# Generated by Django 4.0.5 on 2022-07-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '7. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '8. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '9. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '11. AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '10. Wishlist'},
        ),
    ]
