# Generated by Django 4.0.5 on 2022-07-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_brand_options_alter_cartorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
    ]
