# Generated by Django 4.0.5 on 2022-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_productattribute_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.IntegerField(),
        ),
    ]
